version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    build: ./deployment/es
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - es-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
#    volumes:
#      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 80:9200
  search_service:
    container_name: search_service
    image: "phongvt2004/search_service"
    networks:
      - es-net
    env_file: ".env"
    ports:
      - 80:3000
    depends_on:
      - elasticsearch
networks:
  es-net:
    driver: bridge
