version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    build: ./deployment/es
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  search_service:
    container_name: search_service
    image: "phongvt2004/search_service"
    networks:
      - es-net
    ports:
      - 80:3000
    depends_on:
      - elasticsearch
networks:
  es-net:
    driver: bridge
