name: music_lyrica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  card_swiper: ^3.0.1
  firebase_core: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/logos/
    - assets/images/avatars/
    - assets/images/playlists/
    - assets/images/song_covers/
    - assets/images/artists/
    