name: lyrica_ver2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  card_swiper: ^3.0.1
  audioplayers: ^6.0.0
  firebase_core: ^2.31.1
  get_storage: ^2.1.1
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  lottie: ^3.1.2
  dio: ^5.5.0+1
  file_picker: ^8.0.5
  firebase_storage: ^11.7.7
  gallery_picker: ^0.5.1
  flutter_native_splash: ^2.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  string_similarity: ^2.1.1
  shared_preferences: ^2.2.3
  
  
  
  
  
  
   
  
  
  
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/logos/
    - assets/images/avatars/
    - assets/images/playlists/
    - assets/images/song_covers/
    - assets/images/artists/
    - assets/animations/
