// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8eK9Fn1zQujykIyF8W9OsMZ9tFBBgEjk',
    appId: '1:1099496446199:web:24b88a5d1d094c2701dbf2',
    messagingSenderId: '1099496446199',
    projectId: 'lyrica-f9c90',
    authDomain: 'lyrica-f9c90.firebaseapp.com',
    storageBucket: 'lyrica-f9c90.appspot.com',
    measurementId: 'G-K7NXJ213D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_X1f90qLwmde1Y9Rof0Z4NgBMwcPbxWM',
    appId: '1:1099496446199:android:816ffbac00143c2d01dbf2',
    messagingSenderId: '1099496446199',
    projectId: 'lyrica-f9c90',
    storageBucket: 'lyrica-f9c90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWiFYCRHMEaRadP8KRm8d8xvMMlmq7YB8',
    appId: '1:1099496446199:ios:523520ce57937d5301dbf2',
    messagingSenderId: '1099496446199',
    projectId: 'lyrica-f9c90',
    storageBucket: 'lyrica-f9c90.appspot.com',
    iosBundleId: 'com.example.musicLyrica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWiFYCRHMEaRadP8KRm8d8xvMMlmq7YB8',
    appId: '1:1099496446199:ios:523520ce57937d5301dbf2',
    messagingSenderId: '1099496446199',
    projectId: 'lyrica-f9c90',
    storageBucket: 'lyrica-f9c90.appspot.com',
    iosBundleId: 'com.example.musicLyrica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8eK9Fn1zQujykIyF8W9OsMZ9tFBBgEjk',
    appId: '1:1099496446199:web:099a9d7b3e5d31f301dbf2',
    messagingSenderId: '1099496446199',
    projectId: 'lyrica-f9c90',
    authDomain: 'lyrica-f9c90.firebaseapp.com',
    storageBucket: 'lyrica-f9c90.appspot.com',
    measurementId: 'G-DS4GMCE39Q',
  );
}
